/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;

/**
 *
 * @author malshi parindya
 */
public class Operator extends javax.swing.JFrame {

    /**
     * Creates new form Operator
     */
    public Operator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Pn = new javax.swing.JTextField();
        Ppu = new javax.swing.JTextField();
        Pq = new javax.swing.JTextField();
        Pid = new javax.swing.JTextField();
        addp = new javax.swing.JButton();
        upp = new javax.swing.JButton();
        delp = new javax.swing.JButton();
        Sp = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Cn = new javax.swing.JTextField();
        Cad = new javax.swing.JTextField();
        Cno = new javax.swing.JTextField();
        Cid = new javax.swing.JTextField();
        addc = new javax.swing.JButton();
        upc = new javax.swing.JButton();
        delc = new javax.swing.JButton();
        Sc = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel10 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        addo = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        OCid = new javax.swing.JTextField();
        jTextField34 = new javax.swing.JTextField();
        OCn = new javax.swing.JTextField();
        OCad = new javax.swing.JTextField();
        OCno = new javax.swing.JTextField();
        Oq = new javax.swing.JTextField();
        Oppu = new javax.swing.JTextField();
        Ta = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        Osc = new javax.swing.JButton();
        Osp = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        Opn = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        Opid = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1440, 900));
        setMinimumSize(new java.awt.Dimension(1440, 900));
        setPreferredSize(new java.awt.Dimension(1440, 900));

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setForeground(new java.awt.Color(0, 255, 51));
        jPanel2.setMaximumSize(new java.awt.Dimension(1440, 900));
        jPanel2.setMinimumSize(new java.awt.Dimension(1440, 900));
        jPanel2.setName(""); // NOI18N

        jLabel3.setBackground(new java.awt.Color(0, 153, 153));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 0));
        jLabel3.setText("Operating view");

        jLabel5.setBackground(new java.awt.Color(153, 51, 255));
        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 255));
        jLabel5.setText("New Craft CRM");
        jLabel5.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/Screenshot 2024-04-16 171109.png"))); // NOI18N
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 51, 0), null, null));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/Screenshot 2024-04-16 171109.png"))); // NOI18N
        jLabel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 51, 0), null, null));

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));

        jTabbedPane1.setBackground(new java.awt.Color(0, 204, 51));
        jTabbedPane1.setFont(new java.awt.Font("Trebuchet MS", 2, 12)); // NOI18N

        jPanel5.setBackground(new java.awt.Color(255, 255, 204));

        jButton4.setBackground(new java.awt.Color(102, 255, 102));
        jButton4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jButton4.setText("Logout");
        jButton4.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new java.awt.Color(0, 0, 0)));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Rage Italic", 1, 72)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 0));
        jLabel2.setText("WELCOME!!!");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(393, 393, 393)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(613, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(443, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Home", jPanel5);

        jPanel7.setBackground(new java.awt.Color(255, 255, 204));

        jLabel10.setText("Product name");

        jLabel11.setText("Quantity");

        jLabel12.setText("Price per unit");

        jLabel13.setText("Product id");

        Pn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PnActionPerformed(evt);
            }
        });

        Pid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PidActionPerformed(evt);
            }
        });

        addp.setBackground(new java.awt.Color(255, 204, 204));
        addp.setText("Add");
        addp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addpActionPerformed(evt);
            }
        });

        upp.setText("Update");
        upp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uppActionPerformed(evt);
            }
        });

        delp.setText("Delete");
        delp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delpActionPerformed(evt);
            }
        });

        Sp.setText("Search");
        Sp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel12)
                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(153, 153, 153)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Pid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ppu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pq, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(118, 118, 118)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(upp)
                    .addComponent(addp)
                    .addComponent(delp)
                    .addComponent(Sp))
                .addContainerGap(690, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(Pid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(addp)))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(Pn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(Sp)))
                .addGap(14, 14, 14)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(Pq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Ppu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(delp)))
                .addGap(40, 40, 40)
                .addComponent(upp)
                .addContainerGap(433, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add product", jPanel7);

        jPanel4.setBackground(new java.awt.Color(255, 255, 153));

        jLabel1.setText("Customer name");

        jLabel4.setText("Address");

        jLabel8.setText("Phone number");

        jLabel9.setText("Customer id");

        Cn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CnActionPerformed(evt);
            }
        });

        Cad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadActionPerformed(evt);
            }
        });

        Cid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CidActionPerformed(evt);
            }
        });

        addc.setBackground(new java.awt.Color(255, 204, 204));
        addc.setText("Add");
        addc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcActionPerformed(evt);
            }
        });

        upc.setText("Update");
        upc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upcActionPerformed(evt);
            }
        });

        delc.setText("Delete");
        delc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delcActionPerformed(evt);
            }
        });

        Sc.setText("Search");
        Sc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Cn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(201, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Cno, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cad, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel4))
                                .addGap(199, 199, 199)
                                .addComponent(Cid, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(102, 102, 102)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(upc)
                    .addComponent(addc)
                    .addComponent(delc)
                    .addComponent(Sc))
                .addContainerGap(655, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(Cid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(addc)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Cn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(delc)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(Cad, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(Cno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(Sc)))
                .addGap(36, 36, 36)
                .addComponent(upc)
                .addContainerGap(440, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add customers", jPanel4);

        jPanel9.setBackground(new java.awt.Color(255, 255, 204));

        jPanel10.setBackground(new java.awt.Color(255, 255, 204));

        jLabel44.setText("Order id");

        jLabel45.setText("Customer id");

        jLabel46.setText("Customer name");

        jLabel47.setText("Address");

        jLabel48.setText("Phone number");

        jLabel49.setText("Product id");

        jLabel50.setText("O.Quantity");

        jLabel51.setText("Price per unit");

        jLabel52.setText("Total amount");

        jLabel53.setText("Assign");

        addo.setBackground(new java.awt.Color(255, 204, 204));
        addo.setText("Place the order");
        addo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addoActionPerformed(evt);
            }
        });

        jButton15.setBackground(new java.awt.Color(255, 204, 204));
        jButton15.setText("Delete");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        OCno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OCnoActionPerformed(evt);
            }
        });

        Oq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OqActionPerformed(evt);
            }
        });

        Ta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TaActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---", "Courier1", "Courier2" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        Osc.setText("Search");
        Osc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OscActionPerformed(evt);
            }
        });

        Osp.setText("Search");
        Osp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OspActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(255, 204, 204));
        jButton6.setText("Order Search");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel14.setText("Date");

        jTextField1.setText("   /     /");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        Opn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpnActionPerformed(evt);
            }
        });

        jLabel15.setText("Product");

        jButton1.setBackground(new java.awt.Color(255, 153, 153));
        jButton1.setText("cal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel47)
                    .addComponent(jLabel46)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel53)
                                    .addComponent(jLabel14)
                                    .addComponent(jButton15))
                                .addGap(86, 86, 86)
                                .addComponent(jButton6))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel10Layout.createSequentialGroup()
                                            .addGap(1, 1, 1)
                                            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel44)))
                                        .addComponent(jLabel48)
                                        .addComponent(jLabel50)
                                        .addComponent(jLabel51)
                                        .addComponent(jLabel49))
                                    .addGroup(jPanel10Layout.createSequentialGroup()
                                        .addComponent(jLabel52)
                                        .addGap(30, 30, 30)))
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel10Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(Opid, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel10Layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(OCid)
                                    .addComponent(jTextField34)
                                    .addComponent(OCn)
                                    .addComponent(OCad, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Oq, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Oppu, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Ta, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(OCno, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Opn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(90, 90, 90))
                            .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Osp)
                            .addComponent(Osc))))
                .addContainerGap(529, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel44))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(OCid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Osc))))
                .addGap(31, 31, 31)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel46)
                    .addComponent(OCn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(OCad, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                        .addGap(53, 53, 53))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel47)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel48)
                            .addComponent(OCno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)))
                .addGap(22, 22, 22)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel49)
                    .addComponent(Osp)
                    .addComponent(Opn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(Opid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel50)
                    .addComponent(Oq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel51)
                    .addComponent(Oppu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel52)
                    .addComponent(Ta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(32, 32, 32)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel53)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton15)
                    .addComponent(addo))
                .addGap(50, 50, 50))
        );

        jScrollPane1.setViewportView(jPanel10);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 232, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 267, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Place orders", jPanel9);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1493, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1711, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 376, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(19, 19, 19))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(10, 10, 10))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CidActionPerformed

    private void CnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CnActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void OCnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OCnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OCnoActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/crm_db?useSSL=false","root","Jvd7$mpk");

            String sql= "delete from Orders where order_id =?";
            PreparedStatement pstmt= conn.prepareStatement(sql);
            pstmt.setString (1,jTextField34.getText() );
            
             pstmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Deleted the order");
            jTextField34.setText("");
            OCid.setText("");
          Opid.setText("");
             Oq.setText("");
            Ta.setText("");
          jComboBox2.setSelectedItem("");
            jTextField1.setText("");
            
conn.close();
        }
        catch(Exception e)
        {System.out.println(e.getMessage());}                // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void addpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addpActionPerformed
 try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/crm_db?useSSL=false","root","Jvd7$mpk");

            String sql="insert into product values (?,?,?,?)";
            PreparedStatement pstmt=conn.prepareStatement(sql);
            pstmt.setString (1,Pid.getText() );
            pstmt.setString(2, Pn.getText());
            pstmt.setInt(3,Integer.parseInt( Pq.getText()));
            pstmt.setInt(4, Integer.parseInt(Ppu.getText()));
            
            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Added the Product");
           Pid.setText("");
            Pn.setText("");
            Pq.setText("");
            Ppu.setText("");
    conn.close();
        }
        catch(Exception e)
        {System.out.println(e.getMessage());}        // TODO add your handling code here:
    }//GEN-LAST:event_addpActionPerformed

    private void CadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CadActionPerformed

    private void PidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PidActionPerformed

    private void PnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PnActionPerformed

    private void addcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcActionPerformed
 try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/crm_db?useSSL=false","root","Jvd7$mpk");

            String sql="insert into customer values (?,?,?,?)";
            PreparedStatement pstmt=conn.prepareStatement(sql);
            pstmt.setString (1,Cid.getText() );
            pstmt.setString(2, Cn.getText());
            pstmt.setString(3, Cad.getText());
            pstmt.setString(4, Cno.getText());
            
            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Added the customer");
            Cid.setText("");
            Cn.setText("");
            Cad.setText("");
            Cno.setText("");
           
    conn.close();
        }
        catch(Exception e)
        {System.out.println(e.getMessage());}// TODO add your handling code here:
                                // TODO add your handling code here:
    }//GEN-LAST:event_addcActionPerformed

    private void delcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delcActionPerformed
       try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/crm_db?useSSL=false","root","Jvd7$mpk");

            String sql= "delete from customer where Customer_id =?";
            PreparedStatement pstmt= conn.prepareStatement(sql);
            pstmt.setString (1,Cid.getText() );
            
             pstmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Deleted the customer");
            Cid.setText("");
            Cn.setText("");
            Cad.setText("");
            Cno.setText("");
conn.close();
        }
        catch(Exception e)
        {System.out.println(e.getMessage());}// TODO add your handling code here:
    }//GEN-LAST:event_delcActionPerformed

    private void delpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delpActionPerformed
 try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/crm_db?useSSL=false","root","Jvd7$mpk");

            String sql= "delete from product where Product_id =?";
            PreparedStatement pstmt= conn.prepareStatement(sql);
            pstmt.setString (1,Pid.getText() );
            
             pstmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Deleted the Product");
            Pid.setText("");
            Pn.setText("");
            Pq.setText("");
            Ppu.setText("");
conn.close();
        }
        catch(Exception e)
        {System.out.println(e.getMessage());}        // TODO add your handling code here:
    }//GEN-LAST:event_delpActionPerformed

    private void OqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OqActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void ScActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScActionPerformed
      try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/crm_db?useSSL=false","root","Jvd7$mpk");

            String sql="Select* from Customer where Customer_id=?";
            PreparedStatement pstmt=conn.prepareStatement(sql);
             pstmt.setString (1,Cid.getText() );
             
             ResultSet rs=pstmt.executeQuery();
             
             if(rs.next())
             {Cid.setText(rs.getString("customer_id"));
            Cn.setText(rs.getString("customer_name"));
            Cad.setText(rs.getString("Address"));
            Cno.setText(rs.getString("phone_number"));}
             
             else
             {JOptionPane.showMessageDialog(null, "Record not found");}
            
            conn.close();
        }
        catch(Exception e)
        {System.out.println(e.getMessage());} // TODO add your handling code here:
    }//GEN-LAST:event_ScActionPerformed

    private void SpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpActionPerformed
try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/crm_db?useSSL=false","root","Jvd7$mpk");

            String sql="Select* from Product where product_id=?";
            PreparedStatement pstmt=conn.prepareStatement(sql);
             pstmt.setString (1,Pid.getText() );
             
             ResultSet rs=pstmt.executeQuery();
             
             if(rs.next())
             {Pid.setText(rs.getString("product_id"));
            Pn.setText(rs.getString("product"));
            Pq.setText(rs.getString("quantity"));
            Ppu.setText(rs.getString("price_per_unit"));}
             
             else
             {JOptionPane.showMessageDialog(null, "Record not found");}
            
            conn.close();
        }
        catch(Exception e)
        {System.out.println(e.getMessage());}        // TODO add your handling code here:
    }//GEN-LAST:event_SpActionPerformed

    private void upcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upcActionPerformed
     try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/crm_db?useSSL=false","root","Jvd7$mpk");

            String sql= "update Customer set customer_name=?,Address=?,phone_number=? where customer_id=?  ";
            PreparedStatement pstmt=conn.prepareStatement(sql);
            pstmt.setString(1, Cn.getText());
            pstmt.setString(2, Cad.getText());
            pstmt.setString(3, Cno.getText());
            pstmt.setString(4, Cid.getText());
            
            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Updated the customer record");
            Cid.setText("");
            Cn.setText("");
            Cad.setText("");
            Cno.setText("");
            
                     conn.close();
        }
        catch(Exception e)
        {System.out.println(e.getMessage());}// TODO add your handling code here:
    }//GEN-LAST:event_upcActionPerformed

    private void uppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uppActionPerformed
try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/crm_db?useSSL=false","root","Jvd7$mpk");

            String sql= "update Product set product=?,quantity=?,price_per_unit=? where product_id=?  ";
            PreparedStatement pstmt=conn.prepareStatement(sql);
            pstmt.setString(1, Pn.getText());
            pstmt.setString(2, Pq.getText());
            pstmt.setString(3, Ppu.getText());
            pstmt.setString(4, Pid.getText());
            
            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Updated the product record");
            Pid.setText("");
            Pn.setText("");
            Pq.setText("");
            Ppu.setText("");
            
                     conn.close();
        }
        catch(Exception e)
        {System.out.println(e.getMessage());}        // TODO add your handling code here:
    }//GEN-LAST:event_uppActionPerformed

    private void OpnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OpnActionPerformed

    private void OspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OspActionPerformed
try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/crm_db?useSSL=false","root","Jvd7$mpk");

            String sql="Select* from Product where product_id=?";
            PreparedStatement pstmt=conn.prepareStatement(sql);
             pstmt.setString (1,Opid.getText() );
             
             ResultSet rs=pstmt.executeQuery();
             
             if(rs.next())
             {Opid.setText(rs.getString("product_id"));
            Opn.setText(rs.getString("product"));
            Oppu.setText(rs.getString("price_per_unit"));}
             
             else
             {JOptionPane.showMessageDialog(null, "Added");}
            
            conn.close();
        }
        catch(Exception e)
        {System.out.println(e.getMessage());}        // TODO add your handling code here:
    }//GEN-LAST:event_OspActionPerformed

    private void OscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OscActionPerformed
 try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/crm_db?useSSL=false","root","Jvd7$mpk");

            String sql="Select* from Customer where Customer_id=?";
            PreparedStatement pstmt=conn.prepareStatement(sql);
             pstmt.setString (1,OCid.getText() );
             
             ResultSet rs=pstmt.executeQuery();
             
             if(rs.next())
             {OCid.setText(rs.getString("customer_id"));
            OCn.setText(rs.getString("customer_name"));
            OCad.setText(rs.getString("Address"));
            OCno.setText(rs.getString("phone_number"));}
             
             else
             {JOptionPane.showMessageDialog(null, "Added");}
            
            conn.close();
        }
        catch(Exception e)
        {System.out.println(e.getMessage());}        // TODO add your handling code here:
    }//GEN-LAST:event_OscActionPerformed

    private void TaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TaActionPerformed

  
    }//GEN-LAST:event_TaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           try {
        double quantity = Double.parseDouble(Oq.getText());
        double pricePerUnit = Double.parseDouble(Oppu.getText());
        double result = quantity * pricePerUnit;
        Ta.setText(String.valueOf(result)); // Assuming r is a JTextField
    } catch (NumberFormatException e) {
        // Handle if the input values are not valid numbers
        Ta.setText("Invalid input");
    }   // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void addoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addoActionPerformed
try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/crm_db?useSSL=false","root","Jvd7$mpk");

            String sql="insert into Orders values (?,?,?,?,?,?,?)";
            PreparedStatement pstmt=conn.prepareStatement(sql);
            pstmt.setString (1,jTextField34.getText() );
            pstmt.setString(2, OCid.getText());
            pstmt.setString(3, Opid.getText());
            pstmt.setString(4, Oq.getText());
            pstmt.setString(5, Ta.getText());
          String selectedValue = jComboBox2.getSelectedItem().toString();
            pstmt.setString(6, selectedValue);
            pstmt.setString(7, jTextField1.getText());
            
            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Placed the order");
           /* jTextField34.setText("");
            .setText("");
            Cad.setText("");
            Cno.setText("");
             Cno.setText("");
              Cno.setText("");
               Cno.setText("");*/
           
    conn.close();
        }
        catch(Exception e)
        {System.out.println(e.getMessage());}       // TODO add your handling code here:
    }//GEN-LAST:event_addoActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/crm_db?useSSL=false","root","Jvd7$mpk");

            String sql="Select* from Orders where order_id=?";
            PreparedStatement pstmt=conn.prepareStatement(sql);
             pstmt.setString (1,jTextField34.getText() );
             
             ResultSet rs=pstmt.executeQuery();
             
             if(rs.next())
             {jTextField34.setText(rs.getString("order_id"));
            OCid.setText(rs.getString("customer_id"));
          Opid.setText(rs.getString("product_id"));
             Oq.setText(rs.getString("Order_quantity"));
            Ta.setText(rs.getString("total_amount"));
          jComboBox2.setSelectedItem(rs.getString("assign"));
            jTextField1.setText(rs.getString("o_date"));}
             
             else
             {JOptionPane.showMessageDialog(null, "Record not found");}
            
            conn.close();
        }
        catch(Exception e)
        {System.out.println(e.getMessage());}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Operator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Operator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Operator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Operator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Operator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Cad;
    private javax.swing.JTextField Cid;
    private javax.swing.JTextField Cn;
    private javax.swing.JTextField Cno;
    private javax.swing.JTextField OCad;
    private javax.swing.JTextField OCid;
    private javax.swing.JTextField OCn;
    private javax.swing.JTextField OCno;
    private javax.swing.JTextField Opid;
    private javax.swing.JTextField Opn;
    private javax.swing.JTextField Oppu;
    private javax.swing.JTextField Oq;
    private javax.swing.JButton Osc;
    private javax.swing.JButton Osp;
    private javax.swing.JTextField Pid;
    private javax.swing.JTextField Pn;
    private javax.swing.JTextField Ppu;
    private javax.swing.JTextField Pq;
    private javax.swing.JButton Sc;
    private javax.swing.JButton Sp;
    private javax.swing.JTextField Ta;
    private javax.swing.JButton addc;
    private javax.swing.JButton addo;
    private javax.swing.JButton addp;
    private javax.swing.JButton delc;
    private javax.swing.JButton delp;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField34;
    private javax.swing.JButton upc;
    private javax.swing.JButton upp;
    // End of variables declaration//GEN-END:variables
}
